[project]
# Support Python 3.9+.
requires-python = ">=3.9"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[tool.coverage.run]
# disable couldnt-parse: https://github.com/nedbat/coveragepy/issues/1392
disable_warnings = ["couldnt-parse"]
omit = [
    "install.py",
    "test_*.py",
    "./tests/*"
    ]
parallel = true
concurrency = ["thread","multiprocessing"]

[tool.ruff]
line-length = 120
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  #"D",   # pydocstyle   # add later
]
#extend-exclude = ["./tests","./scripts", "install.py"]
extend-exclude = ["./scripts", "install.py"]

[tool.ruff.per-file-ignores]
"photobooth/appconfig.py" = ["E501"]

[tool.ruff.pydocstyle]
convention = "google"