[project]
name = "photobooth app"
requires-python = ">=3.9"
version = "0.0.1"
description = "Photobooth app written in Python"
authors = [{ name = "Michael G", email = "me@mgrl.de" }]
maintainers = [{ name = "Michael G", email = "me@mgrl.de" }]
readme = "README.md"
license = { file = "LICENSE.md" }
urls = { repository = "https://github.com/mgrl/photobooth-app" }

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[tool.coverage.run]
# disable couldnt-parse: https://github.com/nedbat/coveragepy/issues/1392
disable_warnings = ["couldnt-parse"]
omit = [
    "install.py",
    "test_*.py",
    "./tests/*"
    ]
parallel = true
concurrency = ["thread","multiprocessing"]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
select = [
  "E",   # pycodestyle
  "W",   # pycodestyle
  "F",   # pyflakes
  "B",   # bugbear
  "UP",  # pyupgrade
  "I",   # isort
  #"D",   # pydocstyle   # add later
]
ignore = [
  "B008" #used for DI injection
  ]
extend-exclude = ["./scripts", "install.py"]

[tool.ruff.per-file-ignores]
"photobooth/appconfig.py" = ["E501"]

[tool.ruff.pydocstyle]
convention = "google"