name: pytests and coverage

# coverage is made up by multiple runs on different hosts
# self-hosted is a RPI and has hardware attached to test and gain high coverage
# after all jobs finished, coverage is uploaded as described here
# https://about.codecov.io/blog/uploading-code-coverage-in-a-separate-job-on-github-actions/

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libturbojpeg python3-pip libgl1 git
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements-testing.txt ]; then pip install -r requirements-testing.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          python -m pytest -v --cov-report=term --cov-report=xml:coverage.xml --cov ./
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml

  tests-hardware:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libturbojpeg0 python3-pip git libgl1 python3-picamera2
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements-testing.txt ]; then pip install -r requirements-testing.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          python -m pytest -v --cov-report=term --cov-report=xml:coverage-hardware.xml --cov ./
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-hardware
          path: ./coverage-hardware.xml

  upload-to-codecov:
    needs: [tests, tests-hardware]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
