# pytest

name: pytest

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest, self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libturbojpeg
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-testing.txt ]; then pip install -r requirements-testing.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest -v --cov-report=term --cov-report=xml:coverage.xml --cov ./
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
