name: pytest

# coverage is made up by multiple runs on different hosts
# self-hosted is a RPI and has hardware attached to test and gain high coverage
# after all jobs finished, coverage is uploaded as described here
# https://about.codecov.io/blog/uploading-code-coverage-in-a-separate-job-on-github-actions/

on: [push, pull_request]

permissions:
  contents: read

jobs:
  tests:
    env:
      sharing__shareservice_apikey: ${{ secrets.COMMON_SHARESERVICE_APIKEY }}
      sharing__shareservice_url: "http://localhost:8082/dl.php"
      PHP_CLI_SERVER_WORKERS: 6
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: start php built-in server to allow testing shareservice
        run: |
          sed -i '0,/changedefault!/s//${{ secrets.COMMON_SHARESERVICE_APIKEY }}/' extras/shareservice/dl.php
          nohup php -S localhost:8082 -t extras/shareservice/ > phpd.log 2>&1 &
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libturbojpeg python3-pip libgl1 git libcap-dev
      - name: install pdm
        run: |
          pipx install pdm # on hosted pipx is installed
          pdm install
      - name: Run pytest
        run: |
          pdm run test
      - name: output php logs
        if: always()
        run: |
          cat phpd.log
          cat extras/shareservice/php-error.log
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml

  tests-hardware:
    env:
      ## Sets environment variable
      backends__MAIN_BACKEND: Simulated
      hardwareinputoutput__wled_enabled: True
      hardwareinputoutput__wled_serial_port: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
    runs-on: self-hosted
    if: ${{ github.repository_owner == 'photobooth-app' }}

    steps:
      - uses: actions/checkout@v3
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libturbojpeg0 python3-pip git libgl1 python3-picamera2 python3-venv libexif-dev libcap-dev
      - run: pip install --user --upgrade pipx
      - run: pipx install pdm
      - run: pdm venv create --force 3.9 --system-site-packages # incl system site to allow for picamera2 to import
      - run: pdm install # install in-project env
      - name: Test with pytest
        run: |
          pdm run test
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-hardware
          path: ./coverage.xml

  upload-to-codecov:
    needs: [tests, tests-hardware]
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'photobooth-app' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
