# pytest

name: pytest-rpi

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libturbojpeg0
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-testing.txt ]; then pip install -r requirements-testing.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest -v --cov-report=term --cov-report=xml:coverage.xml --cov ./
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true
        #  token: ${{ secrets.CODECOV_TOKEN }}
        #  files: ./coverage.xml
