name: pytest

# coverage is made up by multiple runs on different hosts
# self-hosted is a RPI and has hardware attached to test and gain high coverage
# after all jobs finished, coverage is uploaded as described here
# https://about.codecov.io/blog/uploading-code-coverage-in-a-separate-job-on-github-actions/

on: [push, pull_request]

permissions:
  contents: read

jobs:
  tests:
    env:
      common__shareservice_apikey: ${{ secrets.COMMON_SHARESERVICE_APIKEY }}
      common__shareservice_url: "http://localhost:8082/dl.php"
      PHP_CLI_SERVER_WORKERS: 3
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@verbose
        with:
          php-version: "7.4"
      - name: start php built-in server to test qr code download
        run: |
          sed -i '0,/changedefault!/s//${{ secrets.COMMON_SHARESERVICE_APIKEY }}/' extras/shareservice/dl.php
          nohup php -S localhost:8082 -t extras/shareservice/ > phpd.log 2>&1 &
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pipx install hatch # on hosted pipx is installed
      - name: Install general dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libturbojpeg python3-pip libgl1 git libcap-dev
      - name: Test with pytest
        run: |
          hatch --verbose run test:test
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml

  tests-hardware:
    env:
      ## Sets environment variable
      backends__MAIN_BACKEND: Simulated
      hardwareinputoutput__wled_enabled: True
      hardwareinputoutput__wled_serial_port: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
    runs-on: self-hosted
    if: ${{ github.repository_owner == 'mgrl' }}

    steps:
      - uses: actions/checkout@v3
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libturbojpeg0 python3-pip git libgl1 python3-picamera2 python3-venv libexif-dev libcap-dev
      - run: pip install --user --upgrade pipx
      - run: pipx install hatch
      - run: hatch env prune # clean env
      #- run: hatch config virtualenvs.options.system-site-packages true # currently needed for picamera2/libcamera until https://github.com/raspberrypi/picamera2/issues/503 fixed
      # do not install gphoto2 deps on self-hosted, because there is a virtual ptp device installed manually built from sources.
      # if installing the local source is overridden and virtual ptp device is not found.
      #- name: Install gphoto2 dependencies
      #  run: |
      #    sudo apt-get -y install libexif12 libgphoto2-6 libgphoto2-port12 libltdl7 libgphoto2-dev libexif-dev
      - name: Test with pytest
        run: |
          hatch --verbose run test:test
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-hardware
          path: ./coverage.xml

  upload-to-codecov:
    needs: [tests, tests-hardware]
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'mgrl' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
