name: envtest

on: [push]

jobs:
  envtest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Show environmetn variables"
        run: |
          env
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.BACKENDS__MAIN_BACKEND == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $BACKENDS__MAIN_BACKEND!"
        env:
          First_Name: Mona
      - name: Use variables
        run: |
          echo "repository variable : ${{ vars.BACKENDS__MAIN_BACKEND }}"
