name: envtest

env:
  ## Sets environment variable
  API_KEY: XXXXXXXXXXXX
  BACKENDS__MAIN_BACKEND: TEST123

on: [push]

jobs:
  envtest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - name: step 1
        ## Reference your environment variables
        run: echo "The API key is:${{env.API_KEY}}"
      - name: "Show environmetn variables"
        run: |
          env
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.BACKENDS__MAIN_BACKEND == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $BACKENDS__MAIN_BACKEND!"
        env:
          First_Name: Mona
      - name: Use variables
        run: |
          echo "repository variable : ${{ vars.BACKENDS__MAIN_BACKEND }}"
